# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T14:43:10+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional, Union

from pydantic import AnyUrl, BaseModel, ConfigDict, EmailStr, Field, RootModel, constr


class Type(Enum):
    primary = 'primary'
    secondary = 'secondary'
    home = 'home'
    office = 'office'
    shipping = 'shipping'
    billing = 'billing'
    other = 'other'


class BadRequestResponse(BaseModel):
    detail: Optional[Union[str, Dict[str, Any]]] = Field(
        None,
        description='Contains parameter or domain specific information related to the error and why it occurred.',
    )
    error: Optional[str] = Field(
        None,
        description='Contains an explanation of the status_code as defined in HTTP/1.1 standard (RFC 7231)',
        examples=['Bad Request'],
    )
    message: Optional[str] = Field(
        None,
        description='A human-readable message providing more details about the error.',
        examples=['Invalid Params'],
    )
    ref: Optional[str] = Field(
        None,
        description='Link to documentation of error type',
        examples=['https://developers.apideck.com/errors#requestvalidationerror'],
    )
    status_code: Optional[float] = Field(
        None, description='HTTP status code', examples=[400]
    )
    type_name: Optional[str] = Field(
        None,
        description='The type of error returned',
        examples=['RequestValidationError'],
    )


class CreatedAt(RootModel[datetime]):
    root: datetime = Field(
        ...,
        description='The date and time when the object was created.',
        examples=['2020-09-30T07:43:32.000Z'],
        title='Created at (timestamp)',
    )


class CreatedBy(RootModel[Optional[str]]):
    root: Optional[str] = Field(
        None,
        description='The user who created the object.',
        examples=['12345'],
        title='Created by',
    )


class Currency(Enum):
    UNKNOWN_CURRENCY = 'UNKNOWN_CURRENCY'
    AED = 'AED'
    AFN = 'AFN'
    ALL = 'ALL'
    AMD = 'AMD'
    ANG = 'ANG'
    AOA = 'AOA'
    ARS = 'ARS'
    AUD = 'AUD'
    AWG = 'AWG'
    AZN = 'AZN'
    BAM = 'BAM'
    BBD = 'BBD'
    BDT = 'BDT'
    BGN = 'BGN'
    BHD = 'BHD'
    BIF = 'BIF'
    BMD = 'BMD'
    BND = 'BND'
    BOB = 'BOB'
    BOV = 'BOV'
    BRL = 'BRL'
    BSD = 'BSD'
    BTN = 'BTN'
    BWP = 'BWP'
    BYR = 'BYR'
    BZD = 'BZD'
    CAD = 'CAD'
    CDF = 'CDF'
    CHE = 'CHE'
    CHF = 'CHF'
    CHW = 'CHW'
    CLF = 'CLF'
    CLP = 'CLP'
    CNY = 'CNY'
    COP = 'COP'
    COU = 'COU'
    CRC = 'CRC'
    CUC = 'CUC'
    CUP = 'CUP'
    CVE = 'CVE'
    CZK = 'CZK'
    DJF = 'DJF'
    DKK = 'DKK'
    DOP = 'DOP'
    DZD = 'DZD'
    EGP = 'EGP'
    ERN = 'ERN'
    ETB = 'ETB'
    EUR = 'EUR'
    FJD = 'FJD'
    FKP = 'FKP'
    GBP = 'GBP'
    GEL = 'GEL'
    GHS = 'GHS'
    GIP = 'GIP'
    GMD = 'GMD'
    GNF = 'GNF'
    GTQ = 'GTQ'
    GYD = 'GYD'
    HKD = 'HKD'
    HNL = 'HNL'
    HRK = 'HRK'
    HTG = 'HTG'
    HUF = 'HUF'
    IDR = 'IDR'
    ILS = 'ILS'
    INR = 'INR'
    IQD = 'IQD'
    IRR = 'IRR'
    ISK = 'ISK'
    JMD = 'JMD'
    JOD = 'JOD'
    JPY = 'JPY'
    KES = 'KES'
    KGS = 'KGS'
    KHR = 'KHR'
    KMF = 'KMF'
    KPW = 'KPW'
    KRW = 'KRW'
    KWD = 'KWD'
    KYD = 'KYD'
    KZT = 'KZT'
    LAK = 'LAK'
    LBP = 'LBP'
    LKR = 'LKR'
    LRD = 'LRD'
    LSL = 'LSL'
    LTL = 'LTL'
    LVL = 'LVL'
    LYD = 'LYD'
    MAD = 'MAD'
    MDL = 'MDL'
    MGA = 'MGA'
    MKD = 'MKD'
    MMK = 'MMK'
    MNT = 'MNT'
    MOP = 'MOP'
    MRO = 'MRO'
    MUR = 'MUR'
    MVR = 'MVR'
    MWK = 'MWK'
    MXN = 'MXN'
    MXV = 'MXV'
    MYR = 'MYR'
    MZN = 'MZN'
    NAD = 'NAD'
    NGN = 'NGN'
    NIO = 'NIO'
    NOK = 'NOK'
    NPR = 'NPR'
    NZD = 'NZD'
    OMR = 'OMR'
    PAB = 'PAB'
    PEN = 'PEN'
    PGK = 'PGK'
    PHP = 'PHP'
    PKR = 'PKR'
    PLN = 'PLN'
    PYG = 'PYG'
    QAR = 'QAR'
    RON = 'RON'
    RSD = 'RSD'
    RUB = 'RUB'
    RWF = 'RWF'
    SAR = 'SAR'
    SBD = 'SBD'
    SCR = 'SCR'
    SDG = 'SDG'
    SEK = 'SEK'
    SGD = 'SGD'
    SHP = 'SHP'
    SLL = 'SLL'
    SOS = 'SOS'
    SRD = 'SRD'
    SSP = 'SSP'
    STD = 'STD'
    SVC = 'SVC'
    SYP = 'SYP'
    SZL = 'SZL'
    THB = 'THB'
    TJS = 'TJS'
    TMT = 'TMT'
    TND = 'TND'
    TOP = 'TOP'
    TRC = 'TRC'
    TRY = 'TRY'
    TTD = 'TTD'
    TWD = 'TWD'
    TZS = 'TZS'
    UAH = 'UAH'
    UGX = 'UGX'
    USD = 'USD'
    USN = 'USN'
    USS = 'USS'
    UYI = 'UYI'
    UYU = 'UYU'
    UZS = 'UZS'
    VEF = 'VEF'
    VND = 'VND'
    VUV = 'VUV'
    WST = 'WST'
    XAF = 'XAF'
    XAG = 'XAG'
    XAU = 'XAU'
    XBA = 'XBA'
    XBB = 'XBB'
    XBC = 'XBC'
    XBD = 'XBD'
    XCD = 'XCD'
    XDR = 'XDR'
    XOF = 'XOF'
    XPD = 'XPD'
    XPF = 'XPF'
    XPT = 'XPT'
    XTS = 'XTS'
    XXX = 'XXX'
    YER = 'YER'
    ZAR = 'ZAR'
    ZMK = 'ZMK'
    ZMW = 'ZMW'
    BTC = 'BTC'
    ETH = 'ETH'


class CustomField(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    description: Optional[str] = Field(
        None,
        description='More information about the custom field',
        examples=['Employee Level'],
        title='Description',
    )
    id: str = Field(..., examples=['2389328923893298'], title='ID')
    name: Optional[str] = Field(
        None,
        description='Name of the custom field.',
        examples=['employee_level'],
        title='Name',
    )
    value: Optional[Union[str, float, bool, List[str]]] = None


class Description(RootModel[Optional[str]]):
    root: Optional[str] = Field(
        None,
        description='A description of the object.',
        examples=['A description'],
        title='Description',
    )


class Division(RootModel[Optional[str]]):
    root: Optional[str] = Field(
        None,
        description='The division the person is currently in. Usually a collection of departments or teams or regions.',
        examples=['Europe'],
        title='Division',
    )


class EcommerceAddress(BaseModel):
    city: Optional[str] = Field(
        None,
        description='City of the billing address.',
        examples=['New York'],
        title='City',
    )
    company_name: Optional[str] = Field(
        None,
        description='Company name of the customer',
        examples=['Acme Inc.'],
        title='Company Name',
    )
    country: Optional[constr(max_length=2)] = Field(
        None,
        description='Country of the billing address.',
        examples=['US'],
        title='Country',
    )
    line1: Optional[str] = Field(
        None,
        description='Address line 1 of the billing address.',
        examples=['123 Main Street'],
        title='Address line 1',
    )
    line2: Optional[str] = Field(
        None,
        description='Address line 2 of the billing address.',
        examples=['Apt 1'],
        title='Address line 2',
    )
    postal_code: Optional[str] = Field(
        None,
        description='Postal/ZIP code of the billing address.',
        examples=['10001'],
        title='Postal code',
    )
    state: Optional[str] = Field(
        None,
        description='State/province of the billing address.',
        examples=['NY'],
        title='State',
    )


class Type1(Enum):
    billing = 'billing'
    shipping = 'shipping'
    other = 'other'


class Status(Enum):
    active = 'active'
    archived = 'archived'


class EcommerceCustomersFilter(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    email: Optional[str] = Field(
        None,
        description='Customer email address to filter on',
        examples=['elon@musk.com'],
    )
    phone_number: Optional[str] = Field(
        None,
        description='Customer phone number to filter on',
        examples=['111-111-1111'],
    )


class EcommerceDiscount(BaseModel):
    amount: Optional[str] = Field(
        None,
        description='The fixed amount of the discount.',
        examples=['5.99'],
        title='Discount amount',
    )
    code: Optional[str] = Field(
        None,
        description='The code used to apply the discount.',
        examples=['SUMMER20'],
        title='Discount code',
    )
    percentage: Optional[str] = Field(
        None,
        description='The percentage of the discount.',
        examples=['0.1'],
        title='Discount percentage',
    )


class FulfillmentStatus(Enum):
    pending = 'pending'
    shipped = 'shipped'
    partial = 'partial'
    delivered = 'delivered'
    cancelled = 'cancelled'
    returned = 'returned'
    unknown = 'unknown'


class PaymentStatus(Enum):
    pending = 'pending'
    authorized = 'authorized'
    paid = 'paid'
    partial = 'partial'
    refunded = 'refunded'
    voided = 'voided'
    unknown = 'unknown'


class Option(BaseModel):
    id: Optional[str] = Field(
        None,
        description='A unique identifier for the option.',
        examples=['jkl012'],
        title='Option identifier',
    )
    name: Optional[str] = Field(
        None,
        description='The name of the option.',
        examples=['Color'],
        title='Option Name',
    )
    value: Optional[str] = Field(
        None,
        description='The value of the option.',
        examples=['Silver'],
        title='Option Value',
    )


class EcommerceOrderStatus(Enum):
    active = 'active'
    completed = 'completed'
    cancelled = 'cancelled'
    archived = 'archived'
    unknown = 'unknown'


class EcommerceOrdersFilter(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    email: Optional[str] = Field(
        None,
        description='Customer email address to filter on',
        examples=['elon@musk.com'],
    )


class Option1(BaseModel):
    id: Optional[str] = Field(
        None,
        description='A unique identifier for the option of the product.',
        examples=['1'],
        title='Option ID',
    )
    name: Optional[str] = Field(
        None,
        description='The name of the option for the product.',
        examples=['Color'],
        title='Option Name',
    )
    values: Optional[List[str]] = None


class Option2(BaseModel):
    id: Optional[str] = Field(
        None,
        description='A unique identifier for the option of the variant.',
        examples=['1'],
        title='Option ID',
    )
    name: Optional[str] = Field(
        None,
        description='The name of the option for the variant.',
        examples=['Color'],
        title='Option Name',
    )
    value: Optional[str] = Field(
        None,
        description='The value of the option for the variant.',
        examples=['Silver'],
        title='Option Value',
    )


class Type2(Enum):
    primary = 'primary'
    secondary = 'secondary'
    work = 'work'
    personal = 'personal'
    billing = 'billing'
    other = 'other'


class Email(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    email: EmailStr = Field(..., examples=['elon@musk.com'])
    id: Optional[str] = Field(None, examples=['123'])
    type: Optional[Type2] = Field(None, examples=['primary'])


class FirstName(RootModel[Optional[str]]):
    root: Optional[str] = Field(
        None,
        description='The first name of the person.',
        examples=['Elon'],
        title='First name',
    )


class Gender(Enum):
    male = 'male'
    female = 'female'
    unisex = 'unisex'
    other = 'other'
    not_specified = 'not_specified'


class Id(RootModel[str]):
    root: str = Field(
        ...,
        description='A unique identifier for an object.',
        examples=['12345'],
        title='ID',
    )


class Language(RootModel[Optional[str]]):
    root: Optional[str] = Field(
        None,
        description='language code according to ISO 639-1. For the United States - EN',
        examples=['EN'],
    )


class LastName(RootModel[Optional[str]]):
    root: Optional[str] = Field(
        None,
        description='The last name of the person.',
        examples=['Musk'],
        title='Last name',
    )


class LinkedEcommerceOrder(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Optional[Id] = None
    status: Optional[EcommerceOrderStatus] = None
    total: Optional[str] = Field(
        None,
        description='The total amount of the order.',
        examples=['199.99'],
        title='Order Total',
    )


class Links(BaseModel):
    current: Optional[str] = Field(
        None,
        description='Link to navigate to the current page through the API',
        examples=['https://unify.apideck.com/crm/companies'],
    )
    next: Optional[str] = Field(
        None,
        description='Link to navigate to the previous page through the API',
        examples=[
            'https://unify.apideck.com/crm/companies?cursor=em9oby1jcm06OnBhZ2U6OjM'
        ],
    )
    previous: Optional[str] = Field(
        None,
        description='Link to navigate to the previous page through the API',
        examples=[
            'https://unify.apideck.com/crm/companies?cursor=em9oby1jcm06OnBhZ2U6OjE%3D'
        ],
    )


class Cursors(BaseModel):
    current: Optional[str] = Field(
        None,
        description='Cursor to navigate to the current page of results through the API',
        examples=['em9oby1jcm06OnBhZ2U6OjI='],
    )
    next: Optional[str] = Field(
        None,
        description='Cursor to navigate to the next page of results through the API',
        examples=['em9oby1jcm06OnBhZ2U6OjM='],
    )
    previous: Optional[str] = Field(
        None,
        description='Cursor to navigate to the previous page of results through the API',
        examples=['em9oby1jcm06OnBhZ2U6OjE='],
    )


class Meta(BaseModel):
    cursors: Optional[Cursors] = Field(
        None,
        description='Cursors to navigate to previous or next pages through the API',
    )
    items_on_page: Optional[int] = Field(
        None,
        description='Number of items returned in the data property of the response',
        examples=[50],
    )


class MiddleName(RootModel[Optional[str]]):
    root: Optional[str] = Field(
        None,
        description='Middle name of the person.',
        examples=['D.'],
        title='Middle name',
    )


class NotFoundResponse(BaseModel):
    detail: Optional[Union[str, Dict[str, Any]]] = Field(
        None,
        description='Contains parameter or domain specific information related to the error and why it occurred.',
    )
    error: Optional[str] = Field(
        None,
        description='Contains an explanation of the status_code as defined in HTTP/1.1 standard (RFC 7231)',
        examples=['Not Found'],
    )
    message: Optional[str] = Field(
        None,
        description='A human-readable message providing more details about the error.',
        examples=['Unknown Widget'],
    )
    ref: Optional[str] = Field(
        None,
        description='Link to documentation of error type',
        examples=['https://developers.apideck.com/errors#entitynotfounderror'],
    )
    status_code: Optional[float] = Field(
        None, description='HTTP status code', examples=[404]
    )
    type_name: Optional[str] = Field(
        None, description='The type of error returned', examples=['EntityNotFoundError']
    )


class NotImplementedResponse(BaseModel):
    detail: Optional[Union[str, Dict[str, Any]]] = Field(
        None,
        description='Contains parameter or domain specific information related to the error and why it occurred.',
    )
    error: Optional[str] = Field(
        None,
        description='Contains an explanation of the status_code as defined in HTTP/1.1 standard (RFC 7231)',
        examples=['Not Implemented'],
    )
    message: Optional[str] = Field(
        None,
        description='A human-readable message providing more details about the error.',
        examples=['Unmapped Attribute'],
    )
    ref: Optional[str] = Field(
        None,
        description='Link to documentation of error type',
        examples=['https://developers.apideck.com/errors#mappingerror'],
    )
    status_code: Optional[float] = Field(
        None, description='HTTP status code', examples=[501]
    )
    type_name: Optional[str] = Field(
        None, description='The type of error returned', examples=['MappingError']
    )


class PaymentRequiredResponse(BaseModel):
    detail: Optional[str] = Field(
        None,
        description='Contains parameter or domain specific information related to the error and why it occurred.',
        examples=['You have reached your limit of 2000'],
    )
    error: Optional[str] = Field(
        None,
        description='Contains an explanation of the status_code as defined in HTTP/1.1 standard (RFC 7231)',
        examples=['Payment Required'],
    )
    message: Optional[str] = Field(
        None,
        description='A human-readable message providing more details about the error.',
        examples=['Request Limit Reached'],
    )
    ref: Optional[str] = Field(
        None,
        description='Link to documentation of error type',
        examples=['https://developers.apideck.com/errors#requestlimiterror'],
    )
    status_code: Optional[float] = Field(
        None, description='HTTP status code', examples=[402]
    )
    type_name: Optional[str] = Field(
        None, description='The type of error returned', examples=['RequestLimitError']
    )


class PaymentUnit(Enum):
    hour = 'hour'
    week = 'week'
    month = 'month'
    year = 'year'
    paycheck = 'paycheck'


class Type3(Enum):
    primary = 'primary'
    secondary = 'secondary'
    home = 'home'
    work = 'work'
    office = 'office'
    mobile = 'mobile'
    assistant = 'assistant'
    fax = 'fax'
    direct_dial_in = 'direct-dial-in'
    personal = 'personal'
    other = 'other'


class PhoneNumber(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    area_code: Optional[str] = Field(None, examples=['323'], title='Area code')
    country_code: Optional[str] = Field(None, examples=['1'], title='Country code')
    extension: Optional[str] = Field(None, examples=['105'], title='Phone extension')
    id: Optional[str] = Field(None, examples=['12345'])
    number: constr(min_length=1) = Field(
        ..., examples=['111-111-1111'], title='Phone number'
    )
    type: Optional[Type3] = Field(None, examples=['primary'])


class PhotoUrl(RootModel[Optional[str]]):
    root: Optional[str] = Field(
        None,
        description='The URL of the photo of a person.',
        examples=['https://unavatar.io/elon-musk'],
        title='Photo URL',
    )


class RowVersion(RootModel[Optional[str]]):
    root: Optional[str] = Field(
        None,
        description='A binary value used to detect updates to a object and prevent data conflicts. It is incremented each time an update is made to the object.',
        examples=['1-12345'],
        title='Row version',
    )


class Title(RootModel[Optional[str]]):
    root: Optional[str] = Field(
        None,
        description='The job title of the person.',
        examples=['CEO'],
        title='Job title',
    )


class Detail(BaseModel):
    context: Optional[str] = None
    error: Optional[Dict[str, Any]] = None


class TooManyRequestsResponse(BaseModel):
    detail: Optional[Detail] = None
    error: Optional[str] = Field(
        None,
        description='Contains an explanation of the status_code as defined in HTTP/1.1 standard (RFC 6585)',
        examples=['Too Many Requests'],
    )
    message: Optional[str] = Field(
        None,
        description='A human-readable message providing more details about the error.',
        examples=['Connector Rate Limit Error'],
    )
    ref: Optional[str] = Field(
        None,
        description='Link to documentation of error type',
        examples=['https://developers.apideck.com/errors#connectorratelimiterror'],
    )
    status_code: Optional[float] = Field(
        None, description='HTTP status code', examples=[429]
    )
    type_name: Optional[str] = Field(
        None,
        description='The type of error returned',
        examples=['ConnectorRateLimitError'],
    )


class UnauthorizedResponse(BaseModel):
    detail: Optional[str] = Field(
        None,
        description='Contains parameter or domain specific information related to the error and why it occurred.',
        examples=[
            'Failed to generate valid JWT Session. Verify applicationId is correct'
        ],
    )
    error: Optional[str] = Field(
        None,
        description='Contains an explanation of the status_code as defined in HTTP/1.1 standard (RFC 7231)',
        examples=['Unauthorized'],
    )
    message: Optional[str] = Field(
        None,
        description='A human-readable message providing more details about the error.',
        examples=['Unauthorized Request'],
    )
    ref: Optional[str] = Field(
        None,
        description='Link to documentation of error type',
        examples=['https://developers.apideck.com/errors#unauthorizederror'],
    )
    status_code: Optional[float] = Field(
        None, description='HTTP status code', examples=[401]
    )
    type_name: Optional[str] = Field(
        None, description='The type of error returned', examples=['UnauthorizedError']
    )


class UnexpectedErrorResponse(BaseModel):
    detail: Optional[Union[str, Dict[str, Any]]] = Field(
        None,
        description='Contains parameter or domain specific information related to the error and why it occurred.',
    )
    error: Optional[str] = Field(
        None,
        description='Contains an explanation of the status_code as defined in HTTP/1.1 standard (RFC 7231)',
        examples=['Bad Request'],
    )
    message: Optional[str] = Field(
        None,
        description='A human-readable message providing more details about the error.',
        examples=['Invalid Params'],
    )
    ref: Optional[str] = Field(
        None,
        description='Link to documentation of error type',
        examples=['https://developers.apideck.com/errors#unauthorizederror'],
    )
    status_code: Optional[float] = Field(
        None, description='HTTP status code', examples=[400]
    )
    type_name: Optional[str] = Field(
        None,
        description='The type of error returned',
        examples=['RequestHeadersValidationError'],
    )


class UnifiedId(BaseModel):
    id: str = Field(
        ...,
        description='The unique identifier of the resource',
        examples=['12345'],
        title='Id',
    )


class UnprocessableResponse(BaseModel):
    detail: Optional[str] = Field(
        None,
        description='Contains parameter or domain specific information related to the error and why it occurred.',
        examples=[
            'Unprocessable request, please verify your request headers and body.'
        ],
    )
    error: Optional[str] = Field(
        None,
        description='Contains an explanation of the status_code as defined in HTTP/1.1 standard (RFC 7231)',
        examples=['Unprocessable Entity'],
    )
    message: Optional[str] = Field(
        None,
        description='A human-readable message providing more details about the error.',
        examples=['Invalid State'],
    )
    ref: Optional[str] = Field(
        None,
        description='Link to documentation of error type',
        examples=['https://developers.apideck.com/errors#invalidstateerror'],
    )
    status_code: Optional[float] = Field(
        None, description='HTTP status code', examples=[422]
    )
    type_name: Optional[str] = Field(
        None, description='The type of error returned', examples=['InvalidStateError']
    )


class UpdateEcommerceCustomerResponse(BaseModel):
    data: UnifiedId
    operation: str = Field(..., description='Operation performed', examples=['update'])
    resource: str = Field(
        ..., description='Unified API resource name', examples=['customers']
    )
    service: str = Field(
        ..., description='Apideck ID of service provider', examples=['shopify']
    )
    status: str = Field(..., description='HTTP Response Status', examples=['OK'])
    status_code: int = Field(
        ..., description='HTTP Response Status Code', examples=[200]
    )


class UpdateEcommerceOrderResponse(BaseModel):
    data: UnifiedId
    operation: str = Field(..., description='Operation performed', examples=['update'])
    resource: str = Field(
        ..., description='Unified API resource name', examples=['orders']
    )
    service: str = Field(
        ..., description='Apideck ID of service provider', examples=['shopify']
    )
    status: str = Field(..., description='HTTP Response Status', examples=['OK'])
    status_code: int = Field(
        ..., description='HTTP Response Status Code', examples=[200]
    )


class UpdateProductResponse(BaseModel):
    data: UnifiedId
    operation: str = Field(..., description='Operation performed', examples=['update'])
    resource: str = Field(
        ..., description='Unified API resource name', examples=['products']
    )
    service: str = Field(
        ..., description='Apideck ID of service provider', examples=['shopify']
    )
    status: str = Field(..., description='HTTP Response Status', examples=['OK'])
    status_code: int = Field(
        ..., description='HTTP Response Status Code', examples=[200]
    )


class UpdatedAt(RootModel[Optional[datetime]]):
    root: Optional[datetime] = Field(
        None,
        description='The date and time when the object was last updated.',
        examples=['2020-09-30T07:43:32.000Z'],
        title='Updated at (timestamp)',
    )


class UpdatedBy(RootModel[Optional[str]]):
    root: Optional[str] = Field(
        None,
        description='The user who last updated the object.',
        examples=['12345'],
        title='Updated by',
    )


class Type4(Enum):
    primary = 'primary'
    secondary = 'secondary'
    work = 'work'
    personal = 'personal'
    other = 'other'


class Website(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Optional[str] = Field(None, examples=['12345'])
    type: Optional[Type4] = Field(None, examples=['primary'])
    url: constr(min_length=1) = Field(..., examples=['http://example.com'])


class Address(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    city: Optional[str] = Field(
        None, description='Name of city.', examples=['San Francisco']
    )
    contact_name: Optional[str] = Field(None, examples=['Elon Musk'])
    country: Optional[str] = Field(
        None,
        description='country code according to ISO 3166-1 alpha-2.',
        examples=['US'],
    )
    county: Optional[str] = Field(
        None,
        description='Address field that holds a sublocality, such as a county',
        examples=['Santa Clara'],
    )
    email: Optional[str] = Field(None, examples=['elon@musk.com'])
    fax: Optional[str] = Field(None, examples=['122-111-1111'])
    id: Optional[str] = Field(None, examples=['123'])
    latitude: Optional[str] = Field(None, examples=['40.759211'])
    line1: Optional[str] = Field(
        None,
        description='Line 1 of the address e.g. number, street, suite, apt #, etc.',
        examples=['Main street'],
    )
    line2: Optional[str] = Field(
        None, description='Line 2 of the address', examples=['apt #']
    )
    line3: Optional[str] = Field(
        None, description='Line 3 of the address', examples=['Suite #']
    )
    line4: Optional[str] = Field(
        None, description='Line 4 of the address', examples=['delivery instructions']
    )
    longitude: Optional[str] = Field(None, examples=['-73.984638'])
    name: Optional[str] = Field(None, examples=['HQ US'])
    phone_number: Optional[str] = Field(None, examples=['111-111-1111'])
    postal_code: Optional[str] = Field(
        None, description='Zip code or equivalent.', examples=['94104']
    )
    row_version: Optional[RowVersion] = None
    salutation: Optional[str] = Field(None, examples=['Mr'])
    state: Optional[str] = Field(None, description='Name of state', examples=['CA'])
    street_number: Optional[str] = Field(
        None, description='Street number', examples=['25']
    )
    string: Optional[str] = Field(
        None,
        examples=['25 Spring Street, Blackburn, VIC 3130'],
        title="The address string. Some APIs don't provide structured address data.",
    )
    type: Optional[Type] = Field(None, examples=['primary'])
    website: Optional[str] = Field(None, examples=['https://elonmusk.com'])


class CreateEcommerceCustomerResponse(BaseModel):
    data: UnifiedId
    operation: str = Field(..., description='Operation performed', examples=['add'])
    resource: str = Field(
        ..., description='Unified API resource name', examples=['customers']
    )
    service: str = Field(
        ..., description='Apideck ID of service provider', examples=['shopify']
    )
    status: str = Field(..., description='HTTP Response Status', examples=['OK'])
    status_code: int = Field(
        ..., description='HTTP Response Status Code', examples=[200]
    )


class CreateEcommerceOrderResponse(BaseModel):
    data: UnifiedId
    operation: str = Field(..., description='Operation performed', examples=['add'])
    resource: str = Field(
        ..., description='Unified API resource name', examples=['orders']
    )
    service: str = Field(
        ..., description='Apideck ID of service provider', examples=['shopify']
    )
    status: str = Field(..., description='HTTP Response Status', examples=['OK'])
    status_code: int = Field(
        ..., description='HTTP Response Status Code', examples=[200]
    )


class CreateProductResponse(BaseModel):
    data: UnifiedId
    operation: str = Field(..., description='Operation performed', examples=['add'])
    resource: str = Field(
        ..., description='Unified API resource name', examples=['products']
    )
    service: str = Field(
        ..., description='Apideck ID of service provider', examples=['shopify']
    )
    status: str = Field(..., description='HTTP Response Status', examples=['OK'])
    status_code: int = Field(
        ..., description='HTTP Response Status Code', examples=[200]
    )


class DeleteEcommerceCustomerResponse(BaseModel):
    data: UnifiedId
    operation: str = Field(..., description='Operation performed', examples=['delete'])
    resource: str = Field(
        ..., description='Unified API resource name', examples=['customers']
    )
    service: str = Field(
        ..., description='Apideck ID of service provider', examples=['shopify']
    )
    status: str = Field(..., description='HTTP Response Status', examples=['OK'])
    status_code: int = Field(
        ..., description='HTTP Response Status Code', examples=[200]
    )


class DeleteEcommerceOrderResponse(BaseModel):
    data: UnifiedId
    operation: str = Field(..., description='Operation performed', examples=['delete'])
    resource: str = Field(
        ..., description='Unified API resource name', examples=['orders']
    )
    service: str = Field(
        ..., description='Apideck ID of service provider', examples=['shopify']
    )
    status: str = Field(..., description='HTTP Response Status', examples=['OK'])
    status_code: int = Field(
        ..., description='HTTP Response Status Code', examples=[200]
    )


class DeleteProductResponse(BaseModel):
    data: UnifiedId
    operation: str = Field(..., description='Operation performed', examples=['delete'])
    resource: str = Field(
        ..., description='Unified API resource name', examples=['products']
    )
    service: str = Field(
        ..., description='Apideck ID of service provider', examples=['shopify']
    )
    status: str = Field(..., description='HTTP Response Status', examples=['OK'])
    status_code: int = Field(
        ..., description='HTTP Response Status Code', examples=[200]
    )


class Department(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    code: Optional[str] = Field(None, examples=['2'], title='Code')
    created_at: Optional[CreatedAt] = None
    created_by: Optional[CreatedBy] = None
    description: Optional[str] = Field(None, examples=['R&D'], title='Description')
    id: Optional[Id] = None
    name: Optional[str] = Field(
        None, description='Department name', examples=['R&D'], title='Name'
    )
    parent_id: Optional[str] = Field(None, description='Parent ID', examples=['22345'])
    updated_at: Optional[UpdatedAt] = None
    updated_by: Optional[UpdatedBy] = None


class Address1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    city: Optional[str] = Field(
        None, description='City of the customer', examples=['Anytown'], title='City'
    )
    country: Optional[str] = Field(
        None, description='Country of the customer', examples=['US'], title='Country'
    )
    id: Optional[Id] = None
    line1: Optional[str] = Field(
        None,
        description='First line of the street address of the customer',
        examples=['Main street'],
        title='Address Line 1',
    )
    line2: Optional[str] = Field(
        None,
        description='Second line of the street address of the customer',
        examples=['apt #'],
        title='Address Line 2',
    )
    postal_code: Optional[str] = Field(
        None,
        description='Postal code of the customer',
        examples=['12345'],
        title='Postal Code',
    )
    state: Optional[str] = Field(
        None, description='State of the customer', examples=['Ohio'], title='State'
    )
    type: Optional[Type1] = Field(None, examples=['billing'])


class EcommerceCustomer(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    addresses: Optional[List[Address1]] = Field(
        None, description='An array of addresses for the customer.', title='Addresses'
    )
    company_name: Optional[str] = Field(
        None,
        description='Company name of the customer',
        examples=['Acme Inc.'],
        title='Company Name',
    )
    created_at: Optional[CreatedAt] = None
    currency: Optional[Currency] = None
    emails: Optional[List[Email]] = Field(
        None,
        description='An array of email addresses for the customer.',
        title='Email Addresses',
    )
    first_name: Optional[str] = Field(
        None,
        description='First name of the customer',
        examples=['John'],
        title='First Name',
    )
    id: Id
    last_name: Optional[str] = Field(
        None,
        description='Last name of the customer',
        examples=['Doe'],
        title='Last Name',
    )
    name: Optional[str] = Field(
        None,
        description='Full name of the customer',
        examples=['John Doe'],
        title='Full Name',
    )
    orders: Optional[List[LinkedEcommerceOrder]] = None
    phone_numbers: Optional[List[PhoneNumber]] = Field(
        None,
        description='An array of phone numbers for the customer.',
        title='Phone Numbers',
    )
    status: Optional[Status] = Field(
        None,
        description='The current status of the customer',
        examples=['active'],
        title='Customer status',
    )
    updated_at: Optional[UpdatedAt] = None


class EcommerceOrderLineItem(BaseModel):
    description: Optional[str] = Field(
        None,
        description='The description of the product or variant associated with the line item.',
        examples=[
            'Powerful and portable, the MacBook Pro is perfect for professionals and creatives.'
        ],
        title='Description',
    )
    discounts: Optional[List[EcommerceDiscount]] = None
    id: Optional[Id] = None
    name: str = Field(
        ...,
        description='The name of the product or variant associated with the line item.',
        examples=['Midnight 16inch MacBook Pro'],
        title='Name',
    )
    options: Optional[List[Option]] = None
    product_id: Optional[str] = Field(
        None,
        description='A unique identifier for the product associated with the line item.',
        examples=['def456'],
        title='Product ID',
    )
    quantity: str = Field(
        ...,
        description='The quantity of the product or variant associated with the line item.',
        examples=['2'],
        title='Quantity',
    )
    sku: Optional[str] = Field(
        None,
        description='The SKU of the product or variant associated with the line item.',
        examples=['MBP123-16GB-SILVER-13'],
        title='SKU',
    )
    tax_amount: Optional[str] = Field(
        None,
        description='The total tax amount applied to the product or variant associated with the line item.',
        examples=['1.6'],
        title='Tax amount',
    )
    tax_rate: Optional[str] = Field(
        None,
        description='The tax rate applied to the product or variant associated with the line item.',
        examples=['0.08'],
        title='Tax rate',
    )
    total_amount: str = Field(
        ...,
        description='The total amount for the product(s) or variant associated with the line item, including taxes and discounts.',
        examples=['43.18'],
        title='Total amount',
    )
    unit_price: Optional[str] = Field(
        None,
        description='The unit price of the product or variant associated with the line item.',
        examples=['19.99'],
        title='Unit price',
    )
    variant_id: Optional[str] = Field(
        None,
        description='A unique identifier for the variant of the product associated with the line item, if applicable.',
        examples=['ghi789'],
        title='Variant ID',
    )


class Category(BaseModel):
    id: Optional[Id] = None
    name: Optional[str] = Field(
        None,
        description='The name of the category.',
        examples=['Laptops'],
        title='Product Category Name',
    )


class Image(BaseModel):
    id: Optional[Id] = None
    url: Optional[str] = Field(
        None,
        description='The URL of an image of the product.',
        examples=['https://example.com/macbook-pro.jpg'],
        title='Image URL',
    )


class Image1(BaseModel):
    id: Optional[Id] = None
    url: Optional[str] = Field(
        None,
        description='The URL of an image of the variant.',
        examples=['https://example.com/macbook-pro.jpg'],
        title='Image URL',
    )


class Variant(BaseModel):
    id: Optional[str] = Field(
        None,
        description='A unique identifier for the variant of the product.',
        examples=['1'],
        title='Variant ID',
    )
    images: Optional[List[Image1]] = None
    inventory_quantity: Optional[str] = Field(
        None,
        description='The quantity of the variant in stock.',
        examples=['5'],
        title='Inventory Quantity',
    )
    name: Optional[str] = Field(
        None,
        description='The name for the variant, used for displaying to customers.',
        examples=['Midnight 16inch MacBook Pro'],
        title='Variant Name',
    )
    options: Optional[List[Option2]] = None
    price: Optional[str] = Field(
        None,
        description='The price of the variant.',
        examples=['1999.99'],
        title='Variant Price',
    )
    sku: Optional[str] = Field(
        None,
        description='The stock keeping unit of the variant.',
        examples=['MBP123-16GB-SILVER-13'],
        title='Variant SKU',
    )
    weight: Optional[str] = Field(
        None,
        description='The weight of the variant.',
        examples=['1.25'],
        title='Weight',
    )
    weight_unit: Optional[str] = Field(
        None,
        description='The unit of measurement for the weight of the variant.',
        examples=['lb'],
        title='Weight Unit',
    )


class EcommerceProduct(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    categories: Optional[List[Category]] = Field(
        None,
        description='An array of categories for the product, used for organization and searching.',
        title='Product Categories',
    )
    created_at: Optional[CreatedAt] = None
    description: Optional[str] = Field(
        None,
        description='A detailed description of the product.',
        examples=[
            'Powerful and portable, the MacBook Pro is perfect for professionals and creatives.'
        ],
        title='Product Description',
    )
    id: Id
    images: Optional[List[Image]] = Field(
        None,
        description='An array of image URLs for the product.',
        title='Product Images',
    )
    inventory_quantity: Optional[str] = Field(
        None,
        description='The quantity of the product in stock.',
        examples=['10'],
        title='Inventory Quantity',
    )
    name: Optional[str] = Field(
        None,
        description='The name of the product as it should be displayed to customers.',
        examples=['MacBook Pro'],
        title='Product Name',
    )
    options: Optional[List[Option1]] = Field(
        None,
        description='An array of options for the product.',
        title='Product Options',
    )
    price: Optional[str] = Field(
        None,
        description='The price of the product.',
        examples=['1999.99'],
        title='Product Price',
    )
    sku: Optional[str] = Field(
        None,
        description='The stock keeping unit of the product.',
        examples=['MBP123'],
        title='Product SKU',
    )
    status: Optional[Status] = Field(
        None,
        description='The current status of the product (active or archived).',
        examples=['active'],
        title='Product Status',
    )
    tags: Optional[List[str]] = Field(
        None,
        description='An array of tags for the product, used for organization and searching.',
        title='Product Tags',
    )
    updated_at: Optional[UpdatedAt] = None
    variants: Optional[List[Variant]] = None
    weight: Optional[str] = Field(
        None,
        description='The weight of the product.',
        examples=['1.25'],
        title='Product Weight',
    )
    weight_unit: Optional[str] = Field(
        None,
        description='The unit of measurement for the weight of the product.',
        examples=['lb'],
        title='Weight Unit',
    )


class EcommerceStore(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    admin_url: Optional[AnyUrl] = Field(
        None,
        description="The store's admin login URL",
        examples=['https://mybrand.com/admin'],
        title='Store Admin URL',
    )
    created_at: Optional[CreatedAt] = None
    id: Id
    name: Optional[str] = Field(
        None, description="The store's name", examples=['My Store'], title='Store name'
    )
    store_url: Optional[AnyUrl] = Field(
        None,
        description="The store's website URL",
        examples=['https://mybrand.com/shop'],
        title='Store URL',
    )
    updated_at: Optional[UpdatedAt] = None


class GetEcommerceCustomerResponse(BaseModel):
    data: EcommerceCustomer
    operation: str = Field(..., description='Operation performed', examples=['one'])
    resource: str = Field(
        ..., description='Unified API resource name', examples=['customers']
    )
    service: str = Field(
        ..., description='Apideck ID of service provider', examples=['shopify']
    )
    status: str = Field(..., description='HTTP Response Status', examples=['OK'])
    status_code: int = Field(
        ..., description='HTTP Response Status Code', examples=[200]
    )


class GetEcommerceCustomersResponse(BaseModel):
    data: List[EcommerceCustomer]
    links: Optional[Links] = None
    meta: Optional[Meta] = None
    operation: str = Field(..., description='Operation performed', examples=['all'])
    resource: str = Field(
        ..., description='Unified API resource name', examples=['customers']
    )
    service: str = Field(
        ..., description='Apideck ID of service provider', examples=['shopify']
    )
    status: str = Field(..., description='HTTP Response Status', examples=['OK'])
    status_code: int = Field(
        ..., description='HTTP Response Status Code', examples=[200]
    )


class GetProductResponse(BaseModel):
    data: EcommerceProduct
    operation: str = Field(..., description='Operation performed', examples=['one'])
    resource: str = Field(
        ..., description='Unified API resource name', examples=['products']
    )
    service: str = Field(
        ..., description='Apideck ID of service provider', examples=['shopify']
    )
    status: str = Field(..., description='HTTP Response Status', examples=['OK'])
    status_code: int = Field(
        ..., description='HTTP Response Status Code', examples=[200]
    )


class GetProductsResponse(BaseModel):
    data: List[EcommerceProduct]
    links: Optional[Links] = None
    meta: Optional[Meta] = None
    operation: str = Field(..., description='Operation performed', examples=['all'])
    resource: str = Field(
        ..., description='Unified API resource name', examples=['products']
    )
    service: str = Field(
        ..., description='Apideck ID of service provider', examples=['shopify']
    )
    status: str = Field(..., description='HTTP Response Status', examples=['OK'])
    status_code: int = Field(
        ..., description='HTTP Response Status Code', examples=[200]
    )


class GetStoreResponse(BaseModel):
    data: EcommerceStore
    operation: str = Field(..., description='Operation performed', examples=['one'])
    resource: str = Field(
        ..., description='Unified API resource name', examples=['stores']
    )
    service: str = Field(
        ..., description='Apideck ID of service provider', examples=['shopify']
    )
    status: str = Field(..., description='HTTP Response Status', examples=['OK'])
    status_code: int = Field(
        ..., description='HTTP Response Status Code', examples=[200]
    )


class GetStoresResponse(BaseModel):
    data: List[EcommerceStore]
    links: Optional[Links] = None
    meta: Optional[Meta] = None
    operation: str = Field(..., description='Operation performed', examples=['all'])
    resource: str = Field(
        ..., description='Unified API resource name', examples=['stores']
    )
    service: str = Field(
        ..., description='Apideck ID of service provider', examples=['shopify']
    )
    status: str = Field(..., description='HTTP Response Status', examples=['OK'])
    status_code: int = Field(
        ..., description='HTTP Response Status Code', examples=[200]
    )


class LinkedEcommerceCustomer(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    company_name: Optional[str] = Field(
        None,
        description='Company name of the customer',
        examples=['Acme Inc.'],
        title='Company Name',
    )
    emails: Optional[List[Email]] = None
    first_name: Optional[str] = Field(
        None,
        description='First name of the customer',
        examples=['John'],
        title='First Name',
    )
    id: str = Field(
        ...,
        description='The ID of the customer this entity is linked to.',
        examples=['12345'],
        title='Customer ID',
    )
    last_name: Optional[str] = Field(
        None,
        description='Last name of the customer',
        examples=['Doe'],
        title='Last Name',
    )
    name: Optional[str] = Field(
        None,
        description='Full name of the customer',
        examples=['John Doe'],
        title='Full Name',
    )
    phone_numbers: Optional[List[PhoneNumber]] = None


class TrackingItem(BaseModel):
    number: str = Field(
        ...,
        description=' The tracking number associated with the shipment, which can be used to track the progress of the delivery.',
        examples=['1Z9999999999999999'],
        title='Tracking number',
    )
    provider: str = Field(
        ...,
        description='The name or code of the carrier or shipping company that is handling the shipment.',
        examples=['UPS'],
        title='Provider',
    )
    updated_at: Optional[UpdatedAt] = None
    url: Optional[str] = Field(
        None,
        description="The URL of the carrier's tracking page, which can be used to view detailed information about the shipment's progress.",
        examples=['https://www.ups.com/track?tracknum=1Z9999999999999999'],
        title='Tracking url',
    )


class EcommerceOrder(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    billing_address: Optional[EcommerceAddress] = None
    created_at: Optional[CreatedAt] = None
    currency: Optional[Currency] = None
    customer: Optional[LinkedEcommerceCustomer] = None
    discounts: Optional[List[EcommerceDiscount]] = None
    fulfillment_status: Optional[FulfillmentStatus] = Field(
        None,
        description='Current fulfillment status of the order.',
        examples=['shipped'],
        title='Fulfillment status',
    )
    id: Id
    line_items: Optional[List[EcommerceOrderLineItem]] = None
    note: Optional[str] = Field(
        None,
        description='Note for the order.',
        examples=['Special instructions for delivery'],
        title='Note',
    )
    order_number: Optional[str] = Field(
        None,
        description='Order number, if any.',
        examples=['123456789'],
        title='Order number',
    )
    payment_method: Optional[str] = Field(
        None,
        description='Payment method used for this order.',
        examples=['credit_card'],
        title='Payment method',
    )
    payment_status: Optional[PaymentStatus] = Field(
        None,
        description='Current payment status of the order.',
        examples=['paid'],
        title='Payment status',
    )
    shipping_address: Optional[EcommerceAddress] = None
    shipping_cost: Optional[str] = Field(
        None,
        description='Shipping cost, if any.',
        examples=['5.17'],
        title='Shipping cost',
    )
    status: Optional[EcommerceOrderStatus] = None
    sub_total: Optional[str] = Field(
        None,
        description='Sub-total amount, normally before tax.',
        examples=['45.17'],
        title='Sub-total amount',
    )
    total_amount: Optional[str] = Field(
        None, description='Total amount due.', examples=['50.17'], title='Total amount'
    )
    total_discount: Optional[str] = Field(
        None,
        description='Total discount, if any.',
        examples=['5.5'],
        title='Total discount',
    )
    total_tax: Optional[str] = Field(
        None, description='Total tax, if any.', examples=['5.16'], title='Total tax'
    )
    tracking: Optional[List[TrackingItem]] = None
    updated_at: Optional[UpdatedAt] = None


class GetEcommerceOrderResponse(BaseModel):
    data: EcommerceOrder
    operation: str = Field(..., description='Operation performed', examples=['one'])
    resource: str = Field(
        ..., description='Unified API resource name', examples=['orders']
    )
    service: str = Field(
        ..., description='Apideck ID of service provider', examples=['shopify']
    )
    status: str = Field(..., description='HTTP Response Status', examples=['OK'])
    status_code: int = Field(
        ..., description='HTTP Response Status Code', examples=[200]
    )


class GetEcommerceOrdersResponse(BaseModel):
    data: List[EcommerceOrder]
    links: Optional[Links] = None
    meta: Optional[Meta] = None
    operation: str = Field(..., description='Operation performed', examples=['all'])
    resource: str = Field(
        ..., description='Unified API resource name', examples=['orders']
    )
    service: str = Field(
        ..., description='Apideck ID of service provider', examples=['shopify']
    )
    status: str = Field(..., description='HTTP Response Status', examples=['OK'])
    status_code: int = Field(
        ..., description='HTTP Response Status Code', examples=[200]
    )
